
###
GET  http://127.0.0.1:8000/api/banners
Content-Type: 'application/json
Accept: 'application/json

###
GET  http://127.0.0.1:8000/api/banner/1
Content-Type: 'application/json
Accept: 'application/json

###
DELETE   http://127.0.0.1:8000/api/banner/1
Content-Type: 'application/json
Accept: 'application/json